[metadata]
createdAt = 2019-11-05T08:15:30-05:00
description = "File based configuration"

[signing]
type = "file-based-signer"
key-file = "./f17f52151ebef6c7334fad080c5704d77216b732.key"
password-file = "./passwordFile"
