[metadata]
createdAt = 2019-11-05T08:15:30-05:00
description = "File based configuration"

[signing]
type = "file-based-signer"
key-file = "./fe3b557e8fb62b89f4916b721be55ceb828dbd73.key"
password-file = "./passwordFile"
